export const urlssql = {
  home: "/",
  // IN, BETWEEN
  between: "/betweenin",
  in: "/betweenin",
  // CASE
  case: "/case",
  // index
  "clusterd index": "/index",
  index: "/index",
  // constraint
  constraint: "/constraint",
  "not null": "/constraint",
  unique: "/constraint",
  "primary key": "/constraint",
  primary: "/constraint",
  "foreign key": "/constraint",
  foreign: "/constraint",
  check: "/constraint",
  default: "/constraint",
  index: "/constraint",
  "Primary key versus Unique Key": "/constraint",
  "Unique Key versus Primary key": "/constraint",
  "difference between Primary key and Unique Key": "/constraint",
  "difference between Unique Key and Primary key": "/constraint",
  "Primary key and Unique Key": "/constraint",
  "Unique Key and Primary key": "/constraint",
  "Primary key Unique Key": "/constraint",
  "Unique Key Primary key": "/constraint",
  "auto increment": "/constraint",
  // Function vs Stored procedure
  function: "/funcproc",
  "stored procedure": "/funcproc",
  "function versus stored procedure": "/funcproc",
  "stored procedure versus function": "/funcproc",
  "function and stored procedure": "/funcproc",
  "stored procedure and function": "/funcproc",
  "function stored procedure": "/funcproc",
  "stored procedure function": "/funcproc",
  "difference between function and stored procedure": "/funcproc",
  "difference between stored procedure and function": "/funcproc",
  // Having Any All GroupBy Exists
  having: "/havinganyall",
  any: "/havinganyall",
  all: "/havinganyall",
  "group by": "/havinganyall",
  exist: "/havinganyall",
  "order by": "/havinganyall",
  // JOIN
  join: "/join",
  "inner join": "/join",
  "left join": "/join",
  "right join": "/join",
  "full outer join": "/join",
  "self join": "/join",
  //
  like: "/like",
  // sql
  sql: "/sql",
  "structured query language": "/sql",
  "tcp ip": "/sql",
  // Statements
  "create database": "/statements",
  "drop database": "/statements",
  "create table": "/statements",
  "drop table": "/statements",
  "alter table": "/statements",
  "select into": "/statements",
  "insert into": "/statements",
  // subsets
  subset: "/subsets",
  "data definition language": "/subsets",
  "data manipulation language": "/subsets",
  "data control language": "/subsets",
  "transaction control language": "/subsets",
  ddl: "/subsets",
  dml: "/subsets",
  dcl: "/subsets",
  tcl: "/subsets",
  // table vs views
  table: "/tableview",
  view: "/tableview",
  "table versus view": "/tableview",
  "view versus table": "/tableview",
  "difference between table and view": "/tableview",
  "difference between view and table": "/tableview",
  "table and view": "/tableview",
  "view and table": "/tableview",
  "table view": "/tableview",
  "view table": "/tableview",
  relationships: "/tableview",
  entity: "/tableview",
  // transaction
  transaction: "/transaction",
  commit: "/transaction",
  "roll back": "/transaction",
  "commit roll back": "/transaction",
  "roll back commit": "/transaction",
  "commit and roll back": "/transaction",
  "roll back and commit": "/transaction",
  // union
  union: "/union",
  "union all": "/union",
};
