export const pagessql = [
  "home",
  // IN, BETWEEN
  "between",
  "in",
  // CASE
  "case",
  // index
  "clustered index",
  "index",
  // Constraints
  "constraint",
  "not null",
  "unique",
  "primary key",
  "primary",
  "foreign key",
  "foreign",
  "check",
  "default",
  "index",
  "Primary key versus Unique Key",
  "Unique Key versus Primary key",
  "difference between Primary key and Unique Key",
  "difference between Unique Key and Primary key",
  "Primary key and Unique Key",
  "Unique Key and Primary key",
  "Primary key Unique Key",
  "Unique Key Primary key",
  "auto increment",
  // Function vs Stored procedure
  "function",
  "stored procedure",
  "function versus stored procedure",
  "stored procedure versus function",
  "function and stored procedure",
  "stored procedure and function",
  "function stored procedure",
  "stored procedure function",
  "difference between function and stored procedure",
  "difference between stored procedure and function",
  // Having Any All GroupBy Exists
  "having",
  "any",
  "all",
  "group by",
  "exist",
  "order by",
  // JOIN
  "join",
  "inner join",
  "left join",
  "right join",
  "full outer join",
  "self join",
  //
  "like",
  // sql
  "sql",
  "structured query language",
  "tcp ip",
  // Statements
  "create database",
  "drop database",
  "create table",
  "drop table",
  "alter table",
  "select into",
  "insert into",
  // subsets
  "subset",
  "Data Definition Language",
  "Data Manipulation Language",
  "Data Control Language",
  "Transaction Control Language",
  "DDL",
  "DML",
  "DCL",
  "TCL",
  // table vs views
  "table",
  "view",
  "table versus view",
  "view versus table",
  "difference between table and view",
  "difference between view and table",
  "table and view",
  "view and table",
  "table view",
  "view table",
  "relationships",
  "entity",
  // transaction
  "transaction",
  "commit",
  "roll back",
  "commit roll back",
  "roll back commit",
  "commit and roll back",
  "roll back and commit",
  // union
  "union",
  "union all",
];
